language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
    - DJANGO="Django==1.9.12"
    - DJANGO="Django==1.10.5"

# install dependencies
install:
  - pip install $DJANGO
  - pip install .
  - pip install -r requirements-test.txt

# database setup
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

# run tests
script: python manage.py test
