language: python
python:
  - "2.7"
  - "3.4"

# install dependencies
install:
  - pip install .
  - pip install -r requirements.txt

# database setup
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

# run tests
script: python manage.py test
