version: '3.1'

services:
  django:
    build: .
    user: app
    command: runserver 0:8000
    volumes:
      - .:/app
    ports:
      - "127.0.99.1:8000:8000"
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
      DATABASE_URL: postgres://app:app@db:5432/app
      DEBUG: 'on'
      USE_DOCKER: 'on'
    networks:
      datawatch:
    depends_on:
      - db
    restart: always

  db:
    image: postgres:9.6
    user: postgres  # just to make life easier when "docker-compose exec"ing
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      datawatch:

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - "127.0.39.1:15672:15672"  # admin UI; credentials: guest/guest
    volumes:
      - /var/lib/rabbitmq
    restart: always
    networks:
      datawatch:

volumes:
  db_data: {}

networks:
  datawatch: