version: '3.5'

services:
  django:
    build: .
    user: app
    command: runserver 0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      IPYTHONDIR: /app/.ipython
      HISTFILE: /app/.bash_history
    restart: unless-stopped
    networks:
      default:
        aliases:
          - datawatch
    depends_on:
      - db

  db:
    image: postgres:9.6
    user: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - '15672:15672'  # admin UI; credentials: guest/guest
    volumes:
      - /var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - default

volumes:
  db_data: {}

networks:
  default:
    name: rh-dev.eu
    ipam:
      config:
        - subnet: 10.199.0.0/16
